@baseUrl = http://localhost:3005/api
@resourceName = accounts
@id = 0

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=id&_order=asc

###

# @name filter
GET {{baseUrl}}/{{resourceName}}?email_like=anhl&email_like=hoai

###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=2&_limit=3

###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

# {
#   body
# }

###

# @name update
PATCH  {{baseUrl}}/{{resourceName}}/{{id}}
Content-Type: application/json

# {
#   body
# }

###

# @name remove
DELETE  {{baseUrl}}/{{resourceName}}/{{id}}
Content-Type: application/json

###

# @name getAccountsBySchoolId
GET {{baseUrl}}/{{resourceName}}/{{id}}/accounts

###

